-- Private bucket for transfer proof images
insert into storage.buckets (id, name, public)
values ('payment-proofs', 'payment-proofs', false)
on conflict (id) do nothing;

-- Upload: user can upload into their own folder (auth.uid()/...)
create policy "Proof: user upload own folder"
  on storage.objects for insert
  with check (
    bucket_id = 'payment-proofs'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "Proof: user update own folder"
  on storage.objects for update
  using (
    bucket_id = 'payment-proofs'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Read: uploader, or admin. (Runner reads via signed URL generated by app.)
create policy "Proof: user read own"
  on storage.objects for select
  using (
    bucket_id = 'payment-proofs'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "Proof: admin read all"
  on storage.objects for select
  using (bucket_id = 'payment-proofs' and public.is_admin());
